-- Adds face embeddings storage for the face_recognition path.
-- One worker can have multiple embeddings (one per reference photo), stored
-- as an array of 128-dim float arrays. Generated by the face-id service on
-- Railway and used by /api/monitor/analyze + analyze-sequence to pre-identify
-- people before sending to Claude.
--
-- Run once in the Supabase SQL editor.

alter table workers
  add column if not exists face_embeddings jsonb default null;

-- Track when each worker's embeddings were last refreshed, so we can re-embed
-- if reference photos change.
alter table workers
  add column if not exists face_embeddings_updated_at timestamptz default null;

comment on column workers.face_embeddings is
  'Array of 128-dim face embeddings from face-id service. One per reference photo. null = not embedded yet.';
